referenceFileNamesList = ['AcetaldehydeNISTRefMixed2_unused_iter_3.csv']
referenceFormsList = ['xyyy']
collectedFileName = '2-CrotAcetExp#2Truncated_remaining_iter_3.csv'
referencePatternTimeRanges = []
ionizationDataFileName = '_ProvidedIonizationData.csv'
iterativeAnalysis = True
iterationNumber = 3
iterationSuffix = '_iter_3'
unusedMolecules = ['Acetaldehyde', 'CO', 'CO2', 'Ethylene (Ethene)', 'H2', 'H2O']
oldReferenceFileName = ['AcetaldehydeNISTRefMixed2_unused_iter_2.csv']
oldCollectedFileName = ''
nextRefFileName = ['AcetaldehydeNISTRefMixed2_unused_iter_3.csv']
nextExpFileName = '2-CrotAcetExp#2Truncated_remaining_iter_3.csv'
preProcessing = 'yes'
dataAnalysis = 'yes'
dataSimulation = 'yes'
grapher = 'no'
stopAtGraphs = True
timeRangeLimit = 'yes'
timeRangeStart = 176.0
timeRangeFinish = 200.0
specificMolecules = 'yes'
chosenMoleculesNames = ['Acetaldehyde', 'CO', 'CO2', 'Ethylene (Ethene)', 'H2', 'H2O']
specificMassFragments = 'yes'
chosenMassFragments = [2, 18, 26, 27, 28, 29, 31, 39, 41, 44, 45, 56, 57, 70]
moleculeLikelihoods = []
sensitivityValues = []
linearBaselineCorrectionSemiAutomatic = 'no'
baselineType = ['linear']
massesToBackgroundCorrect = [2, 18, 27, 28, 31, 39, 41, 44, 57, 70]
earlyBaselineTimes = [[177.0, 177.1]]
lateBaselineTimes = [[901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [901.0, 902.0], [901.0, 902.0], [496.0, 503.0], [901.0, 902.0], [901.0, 902.0]]
backgroundMassFragment = []
backgroundSlopes = []
backgroundIntercepts = []
interpolateYorN = 'no'
marginalChangeRestriction = 2.0
ignorableDeltaYThreshold = 0.01
dataLowerBound = []
dataUpperBound = []
dataRangeSpecifierYorN = 'no'
signalOrConcentrationRange = 'signal'
csvFile = 'yes'
moleculesToRestrict = []
csvFileName = 'rangestemplate.csv'
bruteIncrements = []
permutationNum = 1000
maxPermutations = 100001
scaleRawDataOption = 'manual'
scaleRawDataFactor = 1.0
measuredReferenceYorN = 'no'
referenceFileStandardTuning = []
createMixedTuningPattern = False
referenceFileExistingTuning = 'AcetaldehydeMeasuredRef.csv'
referenceFileDesiredTuning = 'AcetaldehydeOnlyNISTRef.csv'
referenceCorrectionCoefficients = [0.0, 0.0, 1.0]
referenceCorrectionCoefficients_cov = [0, 0, 0]
extractReferencePatternFromDataOption = 'no'
rpcMoleculesToChange = ['Crotyl Alcohol']
rpcMoleculesToChangeMF = [[70, 57]]
rpcTimeRanges = [[300, 500]]
minimalReferenceValue = 'yes'
referenceValueThreshold = [1.0]
referenceSignificantFragmentThresholds = [0.0]
lowerBoundThresholdChooser = 'no'
massesToLowerBoundThresholdFilter = []
lowerBoundThresholdPercentage = [0.25]
lowerBoundThresholdAbsolute = []
dataSmootherYorN = 'no'
dataSmootherChoice = 'timerange'
dataSmootherTimeRadius = 7
dataSmootherPointRadius = 5
dataSmootherHeadersToConfineTo = []
polynomialOrder = 1
rawSignalThresholdMethod = 'no'
rawSignalThresholdValue = [1e-07]
sensitivityThresholdValue = [1]
rawSignalThresholdDivider = []
rawSignalThresholdLimit = 'no'
rawSignalThresholdLimitPercent = []
negativeAnalyzerYorN = 'no'
NegativeAnalyzerTopNContributors = 5
NegativeAnalyzerBaseNumberOfGridIntervals = 5
calculateUncertaintiesInConcentrations = False
referenceFileUncertainties = 2
collectedFileUncertainties = 'Auto'
referenceCorrectionCoefficientsUncertainties = None
referenceCorrectionCoefficientsIonizationUncertainties = None
answer = 'sls'
uniqueOrCommon = 'common'
slsWeighting = [0, 0, 1, 0]
slsFinish = 'brute'
slsUniquePositiveConcentrationsOnly = False
objectiveFunctionType = 'ssr'
distinguished = 'yes'
fullBrute = 'yes'
SLSUniqueExport = 'yes'
implicitSLScorrection = False
finalOptimization = 'None'
concentrationFinder = 'no'
moleculesTSC_List = 'Acetaldehyde'
TSC_List_Type = 'MultipleReferencePatterns'
moleculeSignalTSC_List = 1.66945
massNumberTSC_List = 29
moleculeConcentrationTSC_List = 0.05
unitsTSC = 'bar'
preProcessedDataOutputName = 'PreProcessedData.csv'
resolvedScaledConcentrationsOutputName = 'ScaledConcentrations.csv'
scaledConcentrationsPercentages = 'ScaledConcentrationPercentages.csv'
concentrationsOutputName = 'ResolvedConcentrations.csv'
simulatedSignalsOutputName = 'SimulatedRawSignals.csv'
TotalConcentrationsOutputName = 'TotalConcentrations.csv'
ExportAtEachStep = 'yes'
generatePercentages = 'no'
checkpoint = 4.4550675
start = 4.0944796
timeSinceLastCheckpoint = 0.2502380000000004
iterationNumber = 3

__var_list__ = ['referenceFileNamesList','referenceFormsList','collectedFileName','referencePatternTimeRanges','ionizationDataFileName','iterativeAnalysis','iterationNumber','iterationSuffix','unusedMolecules','oldReferenceFileName','oldCollectedFileName','nextRefFileName','nextExpFileName','preProcessing','dataAnalysis','dataSimulation','grapher','stopAtGraphs','timeRangeLimit','timeRangeStart','timeRangeFinish','specificMolecules','chosenMoleculesNames','specificMassFragments','chosenMassFragments','moleculeLikelihoods','sensitivityValues','linearBaselineCorrectionSemiAutomatic','baselineType','massesToBackgroundCorrect','earlyBaselineTimes','lateBaselineTimes','backgroundMassFragment','backgroundSlopes','backgroundIntercepts','interpolateYorN','marginalChangeRestriction','ignorableDeltaYThreshold','dataLowerBound','dataUpperBound','dataRangeSpecifierYorN','signalOrConcentrationRange','csvFile','moleculesToRestrict','csvFileName','bruteIncrements','permutationNum','maxPermutations','scaleRawDataOption','scaleRawDataFactor','measuredReferenceYorN','referenceFileStandardTuning','createMixedTuningPattern','referenceFileExistingTuning','referenceFileDesiredTuning','referenceCorrectionCoefficients','referenceCorrectionCoefficients_cov','extractReferencePatternFromDataOption','rpcMoleculesToChange','rpcMoleculesToChangeMF','rpcTimeRanges','minimalReferenceValue','referenceValueThreshold','referenceSignificantFragmentThresholds','lowerBoundThresholdChooser','massesToLowerBoundThresholdFilter','lowerBoundThresholdPercentage','lowerBoundThresholdAbsolute','dataSmootherYorN','dataSmootherChoice','dataSmootherTimeRadius','dataSmootherPointRadius','dataSmootherHeadersToConfineTo','polynomialOrder','rawSignalThresholdMethod','rawSignalThresholdValue','sensitivityThresholdValue','rawSignalThresholdDivider','rawSignalThresholdLimit','rawSignalThresholdLimitPercent','negativeAnalyzerYorN','NegativeAnalyzerTopNContributors','NegativeAnalyzerBaseNumberOfGridIntervals','calculateUncertaintiesInConcentrations','referenceFileUncertainties','collectedFileUncertainties','referenceCorrectionCoefficientsUncertainties','referenceCorrectionCoefficientsIonizationUncertainties','answer','uniqueOrCommon','slsWeighting','slsFinish','slsUniquePositiveConcentrationsOnly','objectiveFunctionType','distinguished','fullBrute','SLSUniqueExport','implicitSLScorrection','finalOptimization','concentrationFinder','moleculesTSC_List','TSC_List_Type','moleculeSignalTSC_List','massNumberTSC_List','moleculeConcentrationTSC_List','unitsTSC','preProcessedDataOutputName','resolvedScaledConcentrationsOutputName','scaledConcentrationsPercentages','concentrationsOutputName','simulatedSignalsOutputName','TotalConcentrationsOutputName','ExportAtEachStep','generatePercentages','checkpoint','start','timeSinceLastCheckpoint','iterationNumber']
chosenMoleculesNames = ['H2O']
chosenMassFragments = [18]
